### ISSUE TITLE
เราจะสัมภาษณ์เรื่องอะไรบ้าง?

### ISSUE THREAD

**Issue by lnwwaveza007** [lnwwaveza007/2566-INT100_G1-02-UntilDawn#1]

**Comment by chaiyanan022** [comment]
เราจะเอาหัวข้ออะไรกันดี

**Comment by Naruedom-sri** [comment]
ชื่อจริง กับชื่อเล่นไหม

**Comment by Kimmie516** [comment]
ชื่อที่ชอบให้เรียก

**Comment by lnwwaveza007** [comment]
ตัวละครที่ชื่นชอบแบบ พวกอนิเมะ มังงะ หรือหนังได้หมดเลย พร้อมรูป

**Comment by Kimmie516** [comment]
ศิลปินที่ชอบฟัง

**Comment by Naruedom-sri** [comment]
สิ่งที่คิดอยากจะทำในชีวิจ ถ้าไม่สนเรื่องเงิน

**Comment by chaiyanan022** [comment]
อาหารที่ชอบกิน

**Comment by Kimmie516** [comment]
คิดว่าตัวเองในอีก5ปีทำอะไรอยู่

**Comment by Butt3rPann** [comment]
วันเกิด

**Comment by Butt3rPann** [comment]
ลิ้ง social media

**Comment by lnwwaveza007** [comment]
เพิ่มๆ เอาเป็น Quote ที่ชอบ แล้วก็ Emoji 3 ตัวแทนใจจ 💯 💯 💯

**Comment by lnwwaveza007** [comment]
โอเครได้ข้อมูลครบแล้วว
