### ISSUE TITLE
จะตั้งชื่อทีมว่าอะไรดี?

### ISSUE THREAD

**Issue by Naruedom-sri** [lnwwaveza007/2566-INT100_G1-02-UntilDawn#2]

**Comment by lnwwaveza007** [comment]
ชื่อทีม TIS ครับ เพราะเป็นการกลับหลังจากคำว่า SIT แสดงถึงแบบเป็นโปรแกรมเมอร์ที่ยืดหยุ่น ปรับเปลี่ยนได้ตามสถานการณ์โลก 55555

**Comment by Naruedom-sri** [comment]
WNSVCO เพราะเป็ฯการเอาอักษรตัวแรกของชื่นเล่นแต่ละคนในกลุ่มมาตั้ง

**Comment by Butt3rPann** [comment]
ทีมโต้รุ่ง  เพราะทุกคนน่าจะเป็นสายทำงานตอนกลางคืน ไม่หลับไม่นอน อยู่ยาวถึงเช้า555

**Comment by chaiyanan022** [comment]
ชื่อ int100-group02 มั้ยเพราะตอนดูชื่อจะได้รู้ว่าเป็นกลุ่มของอะไร

**Comment by teerapatwee** [comment]
ชื่อทีม ตาปรือ เพราะ ไม่หลับไม่นอนทำงานกันยันเช้า

**Comment by lnwwaveza007** [comment]
จากการตัดสินใจขั้นสูงสุดเราจึงใช้ ชื่อ โต้รุ่งเป็นภาษาอังกฤษ !!! UntilDawn!!!!

> ทีมโต้รุ่ง เพราะทุกคนน่าจะเป็นสายทำงานตอนกลางคืน ไม่หลับไม่นอน อยู่ยาวถึงเช้า555

[รูปแนบค๊าบบ](https://www.dropbox.com/scl/fi/ictynnce2nhh9h9eql9ua/Screenshot-2023-08-17-211821.png?rlkey=60axmrfvqsmzyw5r4wtzp6826&dl=0)
